import { Inter } from 'next/font/google';
import NextJsTopLoader from 'nextjs-toploader';
import { Toaster } from 'react-hot-toast';

import ModalProvider from '@/providers/ModalProvider';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';
import ThemeProvider from '@/providers/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            <NextJsTopLoader />
            <ModalProvider />
            <Toaster position="bottom-right" />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
