import { Inter } from 'next/font/google';
import NextJsTopLoader from 'nextjs-toploader';

import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';
import ModalProvider from '@/providers/ModalProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <NextJsTopLoader />
          <ModalProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
